name: containers-test
version: '3.8'

services:
  jenkins:
    container_name: jenkins
    build: ./src/jenkins/docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always