global:
  enabled: true
  # tlsDisable: false

injector:
  enabled: true
  # Use the Vault K8s Image https://github.com/hashicorp/vault-k8s/
  image:
    repository: "hashicorp/vault-k8s"
    tag: "1.3.1"

  resources:
    requests:
      memory: 50Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 250m

server:
  image:
    repository: "hashicorp/vault"
    tag: "1.15.1"

  # These Resource Limits are in line with node requirements in the
  # Vault Reference Architecture for a Small Cluster
  resources:
    requests:
      memory: 50Mi
      cpu: 500m
    limits:
      memory: 16Gi
      cpu: 2000m

  extraEnvironmentVars:
    GOOGLE_REGION: global
    GOOGLE_PROJECT: $GCP_PROJECT_ID
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/gcp-credentials.private.json

  extraVolumes:
  - type: 'secret'
    name: 'kms-creds' #kms-creds

  standalone:
    enabled: false

  # Run Vault in "HA" mode.
  ha:
    enabled: true
    replicas: 1
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "0.0.0.0:8200"
      }

      storage "consul" {
        path = "vault"
        address = "consul-consul-server:8500"
      }

      seal "gcpckms" {
        project     = "$GCP_PROJECT_ID"
        region      = "global"
        key_ring    = "$KEY_RING_NAME"
        crypto_key  = "$KEY_NAME"
      }

# Vault UI
ui:
  enabled: true
  externalPort: 8201
