- name: Instalação de dependências
  hosts: localhost
  vars:
    eso_repo_url: "https://charts.external-secrets.io"
    ingress_nginx_repo_url: "https://kubernetes.github.io/ingress-nginx"
    cert_manager_repo_url: "https://charts.jetstack.io"
  tasks:
    - name: Instalando as dependências do Helm
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 
        extra_args: "--break-system-packages"

    - name: Instalando o Ingress Nginx Controller usando Helm
      kubernetes.core.helm:
        release_name: "ingress-nginx"
        release_namespace: "ingress-nginx"
        chart_ref: "ingress-nginx"
        chart_version: 4.8.0
        chart_repo_url: "{{ ingress_nginx_repo_url  }}"
        create_namespace: true
        wait: true

    - name: Instalando o Cert Manager usando Helm
      kubernetes.core.helm:
        release_name: cert-manager
        release_namespace: default
        chart_ref: cert-manager
        chart_version: 1.13.3
        chart_repo_url: "{{ cert_manager_repo_url  }}"
        wait: true

        set_values:
          - value: installCRDs=true
            value_type: string
    
    - name: Instalando o External Secret Operator(ESO) usando Helm
      kubernetes.core.helm:
        release_name: external-secrets
        release_namespace: external-secrets
        chart_ref: external-secrets
        chart_version: 0.9.8
        chart_repo_url: "{{ eso_repo_url  }}"
        create_namespace: true
        wait: true

        set_values:
          - value: installCRDs=true
            value_type: string