apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: vault
spec:
  provider:
    vault:
      server: "{{ vault_server }}"
      path: "{{ vault_secret_engine_path }}"
      version: "{{ vault_version }}"
      auth:
        tokenSecretRef:
          name: vault-secret-store-token
          key: token
