apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-env-secret-store
spec:
  provider:
    vault:
      server: "{{ vault_server }}"
      path: "{{ vault_secret_engine_path }}"
      version: "{{ vault_version }}"
      auth:
        tokenSecretRef:
          name: vault-env-secret-store-token
          key: token
