- name: Instalação do Vault e suas dependências
  hosts: localhost
  vars:
    hashcorp_repo_url: "https://helm.releases.hashicorp.com"
  vars_files:
    - ../config/kms-config.secret.yaml
  tasks:
    - name: Instalando as dependências
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 
        extra_args: "--break-system-packages"

    - name: Instalando o Consul usando Helm
      kubernetes.core.helm:
        release_name: vault-consul
        release_namespace: vault
        chart_ref: consul
        chart_version: 1.1.2
        chart_repo_url: "{{ hashcorp_repo_url  }}"
        create_namespace: true
        wait: true
        # state: absent

        values_files:
          - ../config/consul-values.yaml

    - name: Instalando o Vault usando Helm
      kubernetes.core.helm:
        release_name: vault-server
        release_namespace: vault
        chart_ref: vault
        chart_version: 0.26.1
        chart_repo_url: "{{ hashcorp_repo_url  }}"
        wait: true
        # state: absent

        values_files:
          - ../config/vault-values.secret.yaml