apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "cert-manager-prod"
  namespace: vault
spec: 
  acme: 
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: {{ .Values.cert_manager.email }}
    privateKeySecretRef: 
      name: "cert-manager-prod"
    solvers: 
      - http01: 
          ingress: 
            class: "nginx"
  
